package com.securevote.repository;

import org.springframework.data.jpa.repository.JpaRepository;

import com.securevote.model.Voter;

/**
 * INTERFACE — Spring Data JPA repository for Voter entities.
 *
 * OOP: Interface — defines the data-access contract.
 * The concrete implementation is generated by Spring at runtime.
 * existsById(String) is inherited from JpaRepository.
 */
public interface VoterRepository extends JpaRepository<Voter, String> {
}
